name: run scraper.py
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute python script
        run: python scraper.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          timestamp=$(date -u)
          git add -A
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/satoshi-sh/leaderboard-tracker
          git commit -a -m "Add more data ${timestamp}" --allow-empty
      - name: push changes
        run: |
          git push
